swagger: "2.0"
info:
  description: "agricola api backend"
  version: "1.0.0"
  title: "Agricola Server"
paths:
  /game/{game_id}:
    post:
      description: "post action to agricola game"
      summary: "post action to agricola game"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "game_id"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Dummy"
      responses:
        405:
          description: "Invalid input"
    get:
      description: "get info of agricola game"
      summary: "get info of agricola game"
      produces:
      - "application/json"
      parameters:
      - name: "game_id"
        in: "path"
        required: true
        type: "string"
      responses:
        405:
          description: "Invalid input"
  /game/history/{game_id}:
    get:
      description: "get history of agricola game"
      summary: "get history of agricola game"
      produces:
      - "application/json"
      parameters:
      - name: "game_id"
        in: "path"
        required: true
        type: "string"
      responses:
        405:
          description: "Invalid input"
  /game:
    post:
      description: "create new game"
      summary: "create new game"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/CreateGame"
      responses:
        405:
          description: "Invalid input"
    get:
      description: "search agricola games"
      summary: "search agricola games"
      produces:
      - "application/json"
      responses:
        405:
          description: "Invalid input"
   
definitions:
  CreateGame:
    type: "object"
    properties:
      players:
        type: "array"
        items:
          $ref: "#/definitions/Player"
  
  Player:
    type: "object"
    properties:
      player_type:
        type: "string"
        enum: [human, ai]
      agent_name:
        type: "string"
        description: "player_typeでaiが指定された時のみ参照"
  
  Dummy:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"